### ISSUE TITLE
Refresh Button

### ISSUE THREAD

**Issue by SandNerd** [jenzz/Android-MultiStateListView#1]
Thanks for a great lib. Is it possible for you to add a refresh button to the empty and error layouts that can be called easily from the specific activity?

**Comment by jenzz** [comment]
You have to define the three state layouts (loading/empty/error) yourself anyway, so you can add whatever views or widgets you like to those layouts. In my demo, just replace the `ImageView` in [error_view.xml](https://github.com/jenzz/Android-MultiStateListView/blob/master/res/layout/error_view.xml) with a `Button`, find & reference it in your `Activity` and you should be ready to go.
