### ISSUE TITLE
Update to Material Design

### ISSUE THREAD

**Issue by mkosik** [jenzz/Android-MultiStateListView#4]
What about updating empty / error states to Material Design styling that also Google's apps use for quite a long time?

**Comment by jenzz** [comment]
Not sure if trolling or serious... :open_mouth:

Are you talking about the memes? They're clearly dummy placeholders not intended to be used in production! :smile: 
You can use `custom:emptyView="@layout/empty_view"` and `custom:errorView="@layout/error_view"` to specify your own empty / error states.
